#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDC_MYICON                              2
#define IDC_SETKML                              3
#define IDD_ABOUTBOX                            103
#define IDM_ABOUT                               104
#define ID_FILE_EXIT                            105
#define IDI_SMALL                               108
#define IDD_DEBUG                               129
#define IDR_DEBUG_TOOLBAR                       130
#define IDR_DEBUG                               132
#define IDD_BREAKEDIT                           133
#define IDD_ENTERBREAK                          134
#define IDD_ENTERADR                            135
#define IDD_ABOUT                               136
#define IDR_DEBUG_MEM                           137
#define IDR_DEBUG_CODE                          138
#define IDD_NEWVALUE                            139
#define IDR_MENU                                140
#define IDB_CHECKBOX                            141
#define IDD_KMLLOG                              142
#define IDD_CHOOSEKML                           143
#define IDD_SETTINGS                            151
#define IDD_NEWSETTINGS                         153
#define IDD_DISASM                              155
#define IDI_HP98X6                              163
#define IDB_216_FONTMAP1                        168
#define IDB_236_FONTMAP1                        172
#define IDB_236C_FONTMAP1                       176
#define IDC_AUTOSAVE                            1000
#define IDC_D_D0                                1000
#define IDC_SETDISC73                           1000
#define IDC_DEBUG_MEM_COL8                      1001
#define IDC_KEEPTIME                            1001
#define IDC_AUTOSAVEONEXIT                      1002
#define IDC_D_SR                                1002
#define IDC_D_CYCLES                            1003
#define IDC_HP8XDIR                             1003
#define IDC_SETROM40                            1003
#define IDC_SETx8                               1003
#define IDC_DEBUG_MEM_COL9                      1004
#define IDC_KMLSCRIPT                           1004
#define IDC_SETDISC72                           1004
#define IDC_AUTHOR                              1005
#define IDC_DEBUG_CODE                          1005
#define IDC_USKEYMAP                            1005
#define IDC_DEBUG_MEM_COL10                     1006
#define IDC_HP98635                             1006
#define IDC_TITLE                               1006
#define IDC_DEBUG_MEM_COL11                     1007
#define IDC_KMLLOG                              1007
#define IDC_DEBUG_MEM_COL12                     1008
#define IDC_NSETx8                              1008
#define IDC_VERSION                             1008
#define IDC_DEBUG_MEM_COL13                     1009
#define IDC_DEBUG_MEM_COL14                     1010
#define IDC_ALWAYSDISPLOG                       1011
#define IDC_DEBUG_MEM_COL15                     1011
#define IDC_D_STACK                             1012
#define IDC_UPDATE                              1012
#define IDC_LICENSE                             1013
#define IDC_DISASM_WIN                          1014
#define IDC_D_DCYCLES                           1014
#define IDC_D_STATE                             1015
#define IDC_SOUND                               1015
#define IDC_DATE                                1016
#define IDC_ADDRESS                             1017
#define IDC_DISASM_ADR                          1018
#define IDC_DISASM_NEXT                         1019
#define IDC_DISASM_COPY                         1020
#define IDC_DEBUG_MEM_ADDR                      1024
#define IDC_DEBUG_MEM_TEXT                      1036
#define IDC_DEBUG_MEM_COL0                      1037
#define IDC_DEBUG_MEM_COL1                      1038
#define IDC_DEBUG_MEM_COL2                      1039
#define IDC_DEBUG_MEM_COL3                      1040
#define IDC_DEBUG_MEM_COL4                      1041
#define IDC_DEBUG_MEM_COL5                      1042
#define IDC_DEBUG_MEM_COL6                      1043
#define IDC_DEBUG_MEM_COL7                      1044
#define IDC_STATIC_REGISTERS                    1045
#define IDC_STATIC_MEMORY                       1046
#define IDC_STATIC_CODE                         1047
#define IDC_STATIC_MISC                         1048
#define IDC_STATIC_MEMORY2                      1049
#define IDC_SETRAM                              1053
#define IDC_NEWVALUE                            1061
#define IDC_ENTERADR                            1062
#define IDC_SETSC10                             1066
#define IDC_SETDISC70                           1067
#define IDC_SETSC071                            1068
#define IDC_SETSC075                            1069
#define IDC_STATIC_BREAKPOINT                   1075
#define IDC_BREAKEDIT_ADD                       1076
#define IDC_BREAKEDIT_DELETE                    1077
#define IDC_BREAKEDIT_WND                       1078
#define IDC_BPCODE                              1096
#define IDC_BPBASIC                             1097
#define IDC_BPACCESS                            1098
#define IDC_BPREAD                              1099
#define IDC_BPWRITE                             1100
#define ID_TOOL_DEBUG                           32771
#define ID_FILE_OPEN                            32772
#define ID_FILE_SAVE                            32773
#define ID_TOOL_RUN                             32774
#define ID_TOOL_STOP                            32775
#define ID_ABOUT                                32776
#define ID_VIEW_RESET                           32777
#define ID_FILE_NEW                             32778
#define ID_FILE_SAVEAS                          32779
#define ID_FILE_CLOSE                           32780
#define ID_BACKUP_SAVE                          32782
#define ID_BACKUP_RESTORE                       32783
#define ID_BACKUP_DELETE                        32784
#define ID_COPY_SCREEN                          32785
#define ID_PASTE_STRING                         32786
#define ID_VIEW_SETTINGS                        32787
#define ID_COPY_STRING                          32788
#define ID_D700_LOAD                            32795
#define ID_D700_SAVE                            32796
#define ID_D701_LOAD                            32797
#define ID_D701_SAVE                            32798
#define ID_D700_EJECT                           32804
#define ID_D701_EJECT                           32805
#define ID_TOOL_DISASM                          32827
#define IDS_APP_TITLE                           40000
#define ID_DEBUG_MEM_GOUSP                      40000
#define ID_TOOL_DEBUGON                         40000
#define IDC_HP98X6                              40001
#define ID_DEBUG_MEM_GOSSP                      40001
#define ID_DEBUG_MEM_GOA0                       40002
#define ID_INT1_LOAD                            40002
#define ID_D720_LOAD                            40003
#define ID_DEBUG_MEM_GOA1                       40003
#define ID_D721_LOAD                            40004
#define ID_DEBUG_MEM_GOA2                       40004
#define ID_DEBUG_MEM_GOA3                       40005
#define ID_H730_LOAD                            40005
#define ID_DEBUG_MEM_GOA4                       40006
#define ID_H740_LOAD                            40006
#define ID_DEBUG_MEM_GOA5                       40007
#define ID_DEBUG_MEM_GOA6                       40008
#define ID_INT0_LOAD                            40008
#define ID_INT0_SAVE                            40009
#define ID_INT0_EJECT                           40010
#define ID_INT1_SAVE                            40011
#define ID_INT1_EJECT                           40012
#define ID_D720_SAVE                            40013
#define ID_D720_EJECT                           40014
#define ID_D721_SAVE                            40015
#define ID_D721_EJECT                           40016
#define ID_H730_EJECT                           40017
#define ID_H740_EJECT                           40018
#define ID_DEBUG_RUN                            40023
#define ID_DEBUG_RUNCURSOR                      40024
#define ID_DEBUG_RUN_TO                         40024
#define ID_DEBUG_STEP                           40025
#define ID_DEBUG_STEP_INTO                      40025
#define ID_DEBUG_STEPOVER                       40026
#define ID_DEBUG_STEP_OVER                      40026
#define ID_DEBUG_BREAK                          40027
#define ID_DEBUG_STEPOUT                        40028
#define ID_DEBUG_STEP_OUT                       40028
#define ID_DEBUG_CANCEL                         40029
#define ID_BREAKPOINTS_SETBREAK                 40030
#define ID_BREAK_SET                            40030
#define ID_BREAKPOINTS_CODEEDIT                 40031
#define ID_BREAKPOINTS_CLEARALL                 40032
#define ID_BREAKPOINTS_EXCEP                    40033
#define ID_DEBUG_CODE_GOADR                     40036
#define ID_DEBUG_CODE_GOPC                      40037
#define ID_DEBUG_CODE_SETPCTOSELECT             40038
#define ID_DEBUG_MEM_GOADR                      40039
#define ID_DEBUG_MEM_GOPC                       40040
#define ID_DEBUG_MEM_FIND                       40044
#define ID_INTR_STEP                            40054
#define ID_INFO_IO                              40056
#define IDC_D_D1                                40061
#define IDC_D_D2                                40062
#define IDC_D_D3                                40063
#define IDC_D_D4                                40064
#define IDC_D_D5                                40065
#define IDC_D_D6                                40066
#define IDC_D_D7                                40067
#define IDC_D_PC                                40079
#define IDC_D_A0                                40080
#define IDC_D_A1                                40081
#define IDC_D_A2                                40082
#define IDC_D_A3                                40083
#define IDC_D_A4                                40084
#define IDC_D_A5                                40085
#define IDC_D_A6                                40086
#define IDC_D_USP                               40087
#define IDC_D_SSP                               40088
#define IDC_D_X                                 40089
#define IDC_D_N                                 40090
#define IDC_D_Z                                 40091
#define IDC_D_V                                 40092
#define IDC_D_C                                 40093
#define IDC_D_I                                 40094
#define IDC_D_T                                 40095
#define IDC_D_S                                 40096
#define IDC_SETROM30L                           40096
#define IDC_NSETx1                              40102
#define IDC_NSETx2                              40103
#define IDC_NSETx3                              40104
#define IDC_NSETx4                              40105
#define IDC_NSETxMAX                            40106
#define IDC_SETx1                               40107
#define IDC_SETx2                               40108
#define IDC_SETx3                               40109
#define IDC_SETx4                               40110
#define IDC_SETxMAX                             40111
#define IDC_DEBUGSTART                          40120
#define IDC_SETROM30                            40131
#define IDC_SETROM20                            40132
#define IDC_SETROM10                            40133
#define IDC_SETDISC74                           40135
